version: '3.8'
services:
  backend:
    image: chris924/solarwatch-backend:latest
    build:
      context: SolarWatch 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      ISSUERSIGNINGKEY: ${ISSUERSIGNINGKEY}
      VALIDISSUERKEY: ${VALIDISSUERKEY}
      VALIDAUDIENCEKEY: ${VALIDAUDIENCEKEY}
    networks:
      - solarwatch-net

  frontend:
    image: chris924/solarwatch-frontend:latest
    build:
      context: frontend/solarwatchfrontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - solarwatch-net

  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - solarwatch-net

networks:
  solarwatch-net:


