version: '3.8'
services:
  solarwatch-app:
    image: solarwatch-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    environment:
      - DB_SERVER=solarwatch-db

  solarwatch-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"