name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Files in Directory   # Add this step to list files
        run: ls -R

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version
      - name: Build and Deploy
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
          IssuerSigningKey: ${{secrets.IssuerSigningKey}}
          ValidIssuerKey: ${{secrets.ValidIssuerKey}}
          ValidAudienceKey: ${{secrets.ValidAudienceKey}}
        run: |
         docker-compose -f docker-compose.yml up -d
         
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Push Docker Compose Image
        run: docker-compose push
        env:
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
      
